name: Main Push Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Node.js einrichten
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Abhängigkeiten installieren
        run: npm install

      - name: ESLint Code-Linting
        run: npm run lint

      - name: Jest Tests ausführen (auch wenn keine Tests vorhanden sind)
        run: npm run test -- --coverage
