name: Main Push Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Node.js einrichten
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Abh채ngigkeiten installieren
        run: npm install

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Node.js einrichten
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Abh채ngigkeiten installieren
        run: npm install

      - name: ESLint Code-Linting
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Node.js einrichten
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Abh채ngigkeiten installieren
        run: npm install

      - name: Jest Tests ausf체hren (auch wenn keine Tests vorhanden sind)
        run: npm run test -- --coverage

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Deployment simulieren
        run: echo "Deployment successful"
